CREATE TABLE IF NOT EXISTS owner (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cep             VARCHAR(255),
    complement      VARCHAR(255),
    cpf             VARCHAR(255),
    created_at      TIMESTAMP,
    email           VARCHAR(255),
    is_adm          BOOLEAN,
    last_update     TIMESTAMP,
    name            VARCHAR(255),
    neighborhood    VARCHAR(255),
    number          VARCHAR(255),
    password        VARCHAR(255),
    phone_number    VARCHAR(255),
    street          VARCHAR(255)
    );

CREATE TABLE IF NOT EXISTS employee (
    id      INT PRIMARY KEY,
    name    VARCHAR(255)
    );

CREATE TABLE IF NOT EXISTS pet (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    age         INT,
    breed       VARCHAR(255),
    coat        VARCHAR(255),
    created_at  TIMESTAMP,
    last_update TIMESTAMP,
    name        VARCHAR(255),
    sex         VARCHAR(255),
    size        VARCHAR(255),
    species     VARCHAR(255),
    owner_id    INT,
    CONSTRAINT fk_pet_owner
    FOREIGN KEY (owner_id) REFERENCES owner(id)
    );

CREATE TABLE IF NOT EXISTS pet_offering (
    id          INT PRIMARY KEY,
    name        VARCHAR(255),
    description VARCHAR(255)
    );

CREATE TABLE IF NOT EXISTS pet_offering_price_and_duration (
    id              INT PRIMARY KEY,
    duration        INT,
    pet_coat        VARCHAR(255),
    pet_size        VARCHAR(255),
    price           DOUBLE PRECISION,
    pet_offering_id INT,
    CONSTRAINT fk_price_offering
    FOREIGN KEY (pet_offering_id) REFERENCES pet_offering(id)
    );

CREATE TABLE IF NOT EXISTS appointment (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP,
    end_date_time   TIMESTAMP,
    is_finished     BOOLEAN,
    last_update     TIMESTAMP,
    observations    VARCHAR(255),
    pet_offerings   VARCHAR(255),
    start_date_time TIMESTAMP,
    taxi_service    BOOLEAN,
    total_price     DOUBLE PRECISION,
    employee_id     INT,
    pet_id          INT,
    CONSTRAINT fk_appointment_employee
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    CONSTRAINT fk_appointment_pet
    FOREIGN KEY (pet_id) REFERENCES pet(id)
    );

CREATE TABLE IF NOT EXISTS employees_has_pet_offerings (
    employee_id      INT NOT NULL,
    pet_offering_id  INT NOT NULL,
    PRIMARY KEY (employee_id, pet_offering_id),
    CONSTRAINT fk_employee_offerings_employee
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    CONSTRAINT fk_employee_offerings_pet_offering
    FOREIGN KEY (pet_offering_id) REFERENCES pet_offering(id)
    );